name: Setup Turbo
description:

inputs:
  package_manager:
    description:
    default: npm

  version:
    description:
    default: latest

runs:
  using: composite
  steps:
    - name: Install Turbo
      run: ${{ inputs.package_manager == 'yarn' && 'yarn global add' || format('{0} install --global', inputs.package_manager) }} turbo@${{ inputs.version }}

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-turbo-

outputs:
  sha:
    description:
    value: ${{ steps.last_workflow_run.outputs.sha }}
